services:
  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: okak-xray-reality
    restart: always
    network_mode: host
    volumes:
      - ./configs/xray/config.server.template.json:/etc/xray/config.json:ro
    cap_add:
      - NET_ADMIN

  amneziawg:
    image: amneziavpn/amneziawg:latest
    container_name: okak-amneziawg
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/amneziawg/awg0.server.template.conf:/etc/wireguard/wg0.conf:ro

  vpn-manager:
    image: node:22-alpine
    container_name: okak-vpn-manager
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
      - "8085:8085"
      - "1080:1080"
    volumes:
      - .:/app
    command: sh -c "npm install && npm start"
