// Сгенерировано tools/gen_android_data.py из okak/knowledge.py и okak/timeinfo.py. Не редактируйте вручную.
package ai.okak.app.core

internal data class Country(val stems: List<String>, val genitive: String, val capital: String)
internal data class City(val stem: String, val zone: String, val label: String)

internal object GeneratedData {
    val COUNTRIES: List<Country> = listOf(
        Country(listOf("росси"), "России", "Москва"),
        Country(listOf("франц"), "Франции", "Париж"),
        Country(listOf("германи"), "Германии", "Берлин"),
        Country(listOf("итали"), "Италии", "Рим"),
        Country(listOf("испани"), "Испании", "Мадрид"),
        Country(listOf("португали"), "Португалии", "Лиссабон"),
        Country(listOf("великобритани", "англи"), "Великобритании", "Лондон"),
        Country(listOf("ирланди"), "Ирландии", "Дублин"),
        Country(listOf("нидерланд", "голланди"), "Нидерландов", "Амстердам"),
        Country(listOf("бельги"), "Бельгии", "Брюссель"),
        Country(listOf("швейцари"), "Швейцарии", "Берн"),
        Country(listOf("австри"), "Австрии", "Вена"),
        Country(listOf("чехи"), "Чехии", "Прага"),
        Country(listOf("польш"), "Польши", "Варшава"),
        Country(listOf("венгри"), "Венгрии", "Будапешт"),
        Country(listOf("греци"), "Греции", "Афины"),
        Country(listOf("швеци"), "Швеции", "Стокгольм"),
        Country(listOf("норвеги"), "Норвегии", "Осло"),
        Country(listOf("финлянди"), "Финляндии", "Хельсинки"),
        Country(listOf("дани"), "Дании", "Копенгаген"),
        Country(listOf("украин"), "Украины", "Киев"),
        Country(listOf("беларус"), "Беларуси", "Минск"),
        Country(listOf("литв"), "Литвы", "Вильнюс"),
        Country(listOf("латви"), "Латвии", "Рига"),
        Country(listOf("эстони"), "Эстонии", "Таллин"),
        Country(listOf("молдов"), "Молдовы", "Кишинёв"),
        Country(listOf("грузи"), "Грузии", "Тбилиси"),
        Country(listOf("армени"), "Армении", "Ереван"),
        Country(listOf("азербайджан"), "Азербайджана", "Баку"),
        Country(listOf("казахстан"), "Казахстана", "Астана"),
        Country(listOf("монголи"), "Монголии", "Улан-Батор"),
        Country(listOf("турци"), "Турции", "Анкара"),
        Country(listOf("иран"), "Ирана", "Тегеран"),
        Country(listOf("египт"), "Египта", "Каир"),
        Country(listOf("китай", "кита"), "Китая", "Пекин"),
        Country(listOf("япони"), "Японии", "Токио"),
        Country(listOf("индии", "инди"), "Индии", "Нью-Дели"),
        Country(listOf("таиланд"), "Таиланда", "Бангкок"),
        Country(listOf("вьетнам"), "Вьетнама", "Ханой"),
        Country(listOf("индонези"), "Индонезии", "Джакарта"),
        Country(listOf("австрали"), "Австралии", "Канберра"),
        Country(listOf("канад"), "Канады", "Оттава"),
        Country(listOf("мексик"), "Мексики", "Мехико"),
        Country(listOf("бразили"), "Бразилии", "Бразилиа"),
        Country(listOf("аргентин"), "Аргентины", "Буэнос-Айрес"),
        Country(listOf("сша", "соединенн штат"), "США", "Вашингтон"),
        Country(listOf("сербии", "серби"), "Сербии", "Белград"),
        Country(listOf("хорватии", "хорват"), "Хорватии", "Загреб"),
        Country(listOf("болгари"), "Болгарии", "София"),
        Country(listOf("румыни"), "Румынии", "Бухарест"),
        Country(listOf("словаки"), "Словакии", "Братислава"),
        Country(listOf("словени"), "Словении", "Любляна"),
        Country(listOf("албани"), "Албании", "Тирана"),
        Country(listOf("исланд"), "Исландии", "Рейкьявик"),
        Country(listOf("пакистан"), "Пакистана", "Исламабад"),
        Country(listOf("саудовск"), "Саудовской Аравии", "Эр-Рияд"),
        Country(listOf("ирак"), "Ирака", "Багдад"),
        Country(listOf("новой зеланд", "зеланди"), "Новой Зеландии", "Веллингтон"),
        Country(listOf("перу"), "Перу", "Лима"),
        Country(listOf("чили"), "Чили", "Сантьяго"),
        Country(listOf("колумби"), "Колумбии", "Богота"),
        Country(listOf("кубы", "кубе"), "Кубы", "Гавана"),
        Country(listOf("марокко"), "Марокко", "Рабат"),
        Country(listOf("нигери"), "Нигерии", "Абуджа"),
        Country(listOf("эфиопи"), "Эфиопии", "Аддис-Абеба"),
        Country(listOf("кени"), "Кении", "Найроби"),
        Country(listOf("юар", "южн африк"), "ЮАР", "Претория"),
    )

    val CITIES: List<City> = listOf(
        City("москв", "Europe/Moscow", "Москве"),
        City("питер", "Europe/Moscow", "Санкт-Петербурге"),
        City("петербург", "Europe/Moscow", "Санкт-Петербурге"),
        City("новосибирск", "Asia/Novosibirsk", "Новосибирске"),
        City("екатеринбург", "Asia/Yekaterinburg", "Екатеринбурге"),
        City("владивосток", "Asia/Vladivostok", "Владивостоке"),
        City("калининград", "Europe/Kaliningrad", "Калининграде"),
        City("камчатк", "Asia/Kamchatka", "Камчатке"),
        City("иркутск", "Asia/Irkutsk", "Иркутске"),
        City("омск", "Asia/Omsk", "Омске"),
        City("минск", "Europe/Minsk", "Минске"),
        City("киев", "Europe/Kyiv", "Киеве"),
        City("алматы", "Asia/Almaty", "Алматы"),
        City("астан", "Asia/Almaty", "Астане"),
        City("лондон", "Europe/London", "Лондоне"),
        City("париж", "Europe/Paris", "Париже"),
        City("берлин", "Europe/Berlin", "Берлине"),
        City("рим", "Europe/Rome", "Риме"),
        City("мадрид", "Europe/Madrid", "Мадриде"),
        City("стамбул", "Europe/Istanbul", "Стамбуле"),
        City("дубай", "Asia/Dubai", "Дубае"),
        City("пекин", "Asia/Shanghai", "Пекине"),
        City("токио", "Asia/Tokyo", "Токио"),
        City("сеул", "Asia/Seoul", "Сеуле"),
        City("дели", "Asia/Kolkata", "Дели"),
        City("сингапур", "Asia/Singapore", "Сингапуре"),
        City("нью-йорк", "America/New_York", "Нью-Йорке"),
        City("нью йорк", "America/New_York", "Нью-Йорке"),
        City("лос-анджелес", "America/Los_Angeles", "Лос-Анджелесе"),
        City("сидне", "Australia/Sydney", "Сиднее"),
        City("каир", "Africa/Cairo", "Каире"),
        City("utc", "UTC", "UTC"),
        City("гринвич", "UTC", "Гринвиче"),
    )
}
